openapi: 3.0.3
info:
  version: 1.0.0
  title: Plastep product information services -spec

security:
  - bearerAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/products:
    get:
      operationId: listProducts
      summary: Lists products.
      description: Lists products.
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Page number. Defaults to 0
          schema:
            type: integer
        - name: pageSize
          in: query
          description: Page size. Defaults to 10
          schema:
            type: integer
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
          headers:
            Total-Count:
              schema:
                type: integer
                format: int64
              description: Total count of products with given filters.
        "default":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/products/{id}:
    get:
      operationId: findProduct
      summary: Find product
      description: Find product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Found product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "default":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          readOnly: true
          type: integer
          format: int32
        message:
          readOnly: true
          type: string

    Product:
      type: object
      description: Single product from source system
      required:
        - id
        - productCode
        - name
        - childProductIds
        - childProductCodes
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Product id from source system
        productCode:
          type: string
          readOnly: true
          description: Product code
        name:
          type: string
          description: Name of the product
        childProductIds:
          type: array
          description: List of child product ids
          readOnly: true
          items:
            type: integer
            format: int64
        childProductCodes:
          type: array
          description: List of child product codes
          readOnly: true
          items:
            type: string